# -*- coding: utf-8 -*-
"""pip Turtle Race

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYMXTEna8n9Zuxhc69Gr3EYn5xgieLIv
"""

!pip install ColabTurtlePlus