
"""Turtle Race

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVxjdoCsG_grlOa71HSLKSVllfByREIc
"""

from ColabTurtlePlus.Turtle import *
from dataclasses import dataclass
from time import sleep
from typing import Dict, List, Optional
import random


@dataclass
class RaceConfig:
    # RaceConfig stores all settings in one place.
    # This makes the project easier to adjust without hunting through the code.
    screen_width: int = 800
    screen_height: int = 500
    start_line: int = -300
    finish_line: int = 250
    track_top: int = 200
    track_width: int = 700
    track_height: int = 400
    min_step: int = 2
    max_step: int = 10
    sprint_chance: float = 0.12
    sprint_bonus_min: int = 5
    sprint_bonus_max: int = 12


@dataclass
class Racer:
    # Racer stores the data for one turtle.
    # The turtle object starts as None because it is created later by ColabTurtlePlus.
    name: str
    color: str
    lane_y: int
    turtle: Optional[object] = None

    @property
    def position(self) -> float:
        # A property lets us use racer.position like a normal variable.
        # Behind the scenes, it reads the turtle's current x-coordinate.
        if self.turtle is None:
            return 0.0
        return self.turtle.xcor()


class RacePredictor:
    """
    RacePredictor is the AI-inspired part of the project.

    It does not use a huge machine learning model, but it uses the same basic idea:
    collect data, calculate features, score each racer, and make a prediction.
    """

    def __init__(self, racers: List[Racer], config: RaceConfig):
        self.racers = racers
        self.config = config

        # movement_history stores every move each racer makes.
        # Example: {"Larry": [5, 8, 3], "Tess": [7, 2, 9]}
        self.movement_history: Dict[str, List[int]] = {racer.name: [] for racer in racers}

        # prediction_history saves the predicted winner after each round.
        # This lets us compare the model's final prediction to the real winner.
        self.prediction_history: List[str] = []

    def record_move(self, racer: Racer, distance: int):
        # Every time a turtle moves, we save that distance as training-style data.
        self.movement_history[racer.name].append(distance)

    def average_speed(self, racer: Racer) -> float:
        moves = self.movement_history[racer.name]

        if not moves:
            return 0.0

        return sum(moves) / len(moves)

    def consistency_score(self, racer: Racer) -> float:
        """
        Consistency rewards racers that move at a steady pace.
        A turtle with wild movement swings is less predictable.
        """
        moves = self.movement_history[racer.name]

        if len(moves) < 2:
            return 1.0

        average = self.average_speed(racer)
        average_difference = sum(abs(move - average) for move in moves) / len(moves)

        # Higher number means more consistent.
        return 1 / (1 + average_difference)

    def distance_remaining(self, racer: Racer) -> float:
        return max(0, self.config.finish_line - racer.position)

    def score_racer(self, racer: Racer) -> float:
        """
        Creates one prediction score for a racer.

        This is a simple heuristic model:
        - current position matters most
        - average speed helps estimate future movement
        - consistency gives a small bonus
        - distance remaining is a penalty
        """
        position_score = racer.position
        speed_score = self.average_speed(racer) * 8
        consistency_bonus = self.consistency_score(racer) * 15
        distance_penalty = self.distance_remaining(racer) * 0.15

        return position_score + speed_score + consistency_bonus - distance_penalty

    def predict_winner(self) -> Racer:
        predicted_winner = max(self.racers, key=self.score_racer)
        self.prediction_history.append(predicted_winner.name)
        return predicted_winner

    def win_probabilities(self) -> Dict[str, float]:
        """
        Converts racer scores into percent-style probabilities.
        This is similar to how ML models turn raw scores into predictions.
        """
        scores = {racer.name: max(1, self.score_racer(racer)) for racer in self.racers}
        total_score = sum(scores.values())

        return {
            racer_name: round((score / total_score) * 100, 1)
            for racer_name, score in scores.items()
        }

    def print_prediction_report(self, actual_winners: List[Racer]):
        actual_winner_names = [winner.name for winner in actual_winners]
        final_prediction = self.prediction_history[-1] if self.prediction_history else "No prediction"
        probabilities = self.win_probabilities()

        print("\nAI Prediction Report")
        print("--------------------")
        print(f"Final predicted winner: {final_prediction}")
        print(f"Actual winner(s): {', '.join(actual_winner_names)}")
        print(f"Prediction correct: {final_prediction in actual_winner_names}")

        print("\nEstimated win probabilities")
        for racer_name, probability in probabilities.items():
            print(f"{racer_name}: {probability}%")

        print("\nAverage speed by racer")
        for racer in self.racers:
            print(f"{racer.name}: {round(self.average_speed(racer), 2)} pixels per round")


class TurtleRace:
    def __init__(self, racers: List[Racer], config: Optional[RaceConfig] = None):
        self.racers = racers
        self.config = config or RaceConfig()
        self.predictor = RacePredictor(self.racers, self.config)
        self.rounds = 0

    def write_text(self, x: int, y: int, message: str, text_color="white", size=18, style="bold"):
        # Reusable helper for drawing centered text on the screen.
        penup()
        goto(x, y)
        color(text_color)
        write(message, align="center", font=("Arial", size, style))

    def draw_rectangle(self, x: int, y: int, width: int, height: int, fill_color: str):
        # Reusable helper for drawing filled rectangles like the track and text cover-up area.
        penup()
        goto(x, y)
        pendown()
        color(fill_color)
        begin_fill()
        for _ in range(2):
            forward(width)
            right(90)
            forward(height)
            right(90)
        end_fill()
        penup()

    def draw_track(self):
        # Sets up the whole visual race track.
        clearscreen()
        setup(self.config.screen_width, self.config.screen_height)
        bgcolor("darkgreen")
        speed(0)
        hideturtle()

        track_left = -self.config.track_width // 2
        self.draw_rectangle(
            track_left,
            self.config.track_top,
            self.config.track_width,
            self.config.track_height,
            "saddlebrown",
        )
        self.write_text(0, 220, "TURTLE GRAND PRIX", "gold", 24)
        self.write_text(0, 195, "First turtle to the checkered flag wins", "white", 12, "normal")
        self.draw_start_line()
        self.draw_lane_markers()
        self.draw_finish_line()
        done()

    def draw_start_line(self):
        # Draws the vertical start line where each racer begins.
        penup()
        goto(self.config.start_line, 185)
        pendown()
        color("white")
        pensize(4)
        goto(self.config.start_line, -185)
        penup()
        pensize(1)
        self.write_text(self.config.start_line, 205, "START", "white", 12)

    def draw_lane_markers(self):
        # Draws dashed lines between the race lanes.
        color("tan")
        pensize(2)

        for y in [100, 0, -100]:
            penup()
            goto(-335, y)
            pendown()
            for _ in range(28):
                forward(14)
                penup()
                forward(10)
                pendown()

        penup()
        pensize(1)

    def draw_finish_line(self):
        # Draws a checkered finish line using square stamps.
        gap_size = 20
        shape("square")
        penup()

        for row in range(20):
            for column in range(2):
                is_white_square = (row + column) % 2 == 0
                color("white" if is_white_square else "black")
                goto(self.config.finish_line + column * gap_size, 190 - row * gap_size)
                stamp(layer=1)

        self.write_text(self.config.finish_line + 55, 210, "FINISH", "white", 12)

    def create_racers(self):
        # Creates each turtle racer from the Racer data objects.
        for racer in self.racers:
            racer.turtle = Turtle()
            racer.turtle.shape("turtle2")
            racer.turtle.color(racer.color)
            racer.turtle.penup()
            racer.turtle.goto(self.config.start_line, racer.lane_y)
            racer.turtle.pendown()
            self.draw_racer_label(racer)

        done()

    def draw_racer_label(self, racer: Racer):
        # Writes each turtle's name beside its lane.
        penup()
        goto(self.config.start_line - 45, racer.lane_y - 8)
        color(racer.color)
        write(racer.name, align="right", font=("Arial", 11, "bold"))

    def countdown(self):
        # Adds a short countdown before the race starts.
        for message in ["3", "2", "1", "GO!"]:
            self.write_text(0, -225, message, "gold", 22)
            sleep(0.6)
            self.draw_rectangle(-45, -205, 90, 35, "saddlebrown")
            done()

    def calculate_move_distance(self) -> int:
        # Random movement keeps the race unpredictable.
        distance = random.randint(self.config.min_step, self.config.max_step)

        # Some turns get a sprint bonus, which creates exciting comeback moments.
        if random.random() < self.config.sprint_chance:
            distance += random.randint(self.config.sprint_bonus_min, self.config.sprint_bonus_max)

        return distance

    def move_racers(self):
        # Moves each turtle and sends that movement data to the predictor.
        for racer in self.racers:
            distance = self.calculate_move_distance()
            racer.turtle.forward(distance)
            self.predictor.record_move(racer, distance)

    def get_leading_position(self) -> float:
        # Finds the farthest x-position reached by any turtle.
        return max(racer.position for racer in self.racers)

    def race_is_finished(self) -> bool:
        # The race ends once any turtle reaches or passes the finish line.
        return self.get_leading_position() >= self.config.finish_line

    def run_race(self):
        while not self.race_is_finished():
            self.rounds += 1
            self.move_racers()
            predicted_winner = self.predictor.predict_winner()

            # Every 5 rounds, print the current prediction to the notebook output.
            # This shows the model updating as it receives new data.
            if self.rounds % 5 == 0:
                print(f"Round {self.rounds}: AI predicts {predicted_winner.name} is most likely to win.")

    def get_winners(self) -> List[Racer]:
        # Handles ties by returning every racer with the leading position.
        leading_position = self.get_leading_position()
        return [racer for racer in self.racers if racer.position == leading_position]

    def celebrate(self, winners: List[Racer]):
        # Spins the winner or winners after the race.
        for winner in winners:
            winner.turtle.speed(5)
            winner.turtle.left(360)

    def display_results(self, winners: List[Racer]):
        # Displays the final result on the race screen.
        winner_names = [winner.name for winner in winners]

        if len(winners) == 1:
            result_text = f"{winner_names[0]} wins the Turtle Grand Prix!"
        else:
            result_text = f"It's a tie between {', '.join(winner_names)}!"

        hideturtle()
        self.write_text(0, -225, result_text, "gold", 18)
        self.write_text(0, -245, f"Race finished in {self.rounds} rounds", "white", 11, "normal")
        done()

    def print_scoreboard(self):
        # Sorts racers from first to last based on final position.
        ranked_racers = sorted(self.racers, key=lambda racer: racer.position, reverse=True)

        print("\nFinal Race Results")
        print("------------------")
        for place, racer in enumerate(ranked_racers, start=1):
            print(f"{place}. {racer.name}: {round(racer.position, 1)}")

    def start(self):
        # Main game flow: setup, countdown, race, celebrate, and report.
        random.seed()
        self.draw_track()
        self.create_racers()
        self.countdown()
        self.run_race()

        winners = self.get_winners()
        self.celebrate(winners)
        self.display_results(winners)
        self.print_scoreboard()
        self.predictor.print_prediction_report(winners)


def main():
    racers = [
        Racer("Larry", "cyan", 150),
        Racer("Tess", "magenta", 50),
        Racer("Scott", "yellow", -50),
        Racer("Mary", "lime", -150),
    ]

    game = TurtleRace(racers)
    game.start()


if __name__ == "__main__":
    main()
